# Generated by Django 5.2.16 on 2026-08-18 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Client-supplied key. A retry carrying a key already seen returns the original order instead of creating a second one.', max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('customer', 'idempotency_key'), name='order_unique_customer_idempotency_key'),
        ),
    ]
