# Generated by Django 5.2.16 on 2026-08-05 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("sku",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price__gte", 0)),
                        name="product_price_non_negative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delta",
                    models.IntegerField(
                        help_text="Signed change in units: negative for a sale, positive for a restock."
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("order", "Order"),
                            ("restock", "Restock"),
                            ("adjustment", "Adjustment"),
                            ("cancellation", "Cancellation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["product", "-created_at"],
                        name="inventory_s_product_cfb4fb_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("delta", 0), _negated=True),
                        name="stockmovement_delta_non_zero",
                    )
                ],
            },
        ),
    ]
